import { BlogModel } from './models/blog-model';

export const Blogs: BlogModel[] = [
    {
        ID: 1,
        Show: true,
        Title: "IM Wales 2018",
        Date: new Date('2018-09-09'),
        Image: 'assets/wales2018.jpg',
        Swim: 4120000, Bike: 21813000, Run: 13273000, Overall: 39206000,
        Body: `Following an analysis day with Oliver Harkin in February, I decided to go all in on 2018 with coaching. I was already signed up for Austria and figured I may as well throw Wales into the mix as well, having promised myself months earlier never again to register for multiple Ironman events in one year…that didn’t last long. Wales 2017 was a pretty special race for me, getting PBs on both the swim and run despite a tough course. I was left wondering if I could do more on that bike course.
        <br /><br />
        I managed a decent time out in Austria, just falling short of a sub 10. It was frustrating not to have an opportunity to nip that goal in the bud on another fast course but I would have to be patient for now (sub 10 in Wales would win my age group!). Recovery was pretty good until I decided to try my luck at tag rugby…they were short on numbers and I figured I’d be brilliant at it. It turns out I’m only able to run in straight lines and borrowing a pair of football boots wasn’t a great idea. This meant the lead up with to Tyrone 70.3 missed run training but a decent bike split in the entire average rainfall for July afforded me 2nd place in AG and was a great booster ahead of Wales in 6 weeks time.
        <br /><br />
        I lost all enthusiasm for swimming but training was otherwise on track and I was soon on the ferry to Fishguard to explore the Welsh castles and their many staircases, probably not an optimal taper. I did at least get a few swims down at Tenby, which despite what you will see if you look up footage from 2015 is usually flat and well sheltered. I met up with parents on the Saturday and began the usual preparations ahead of race day, in bed by 10.
        <br /><br />
        Alarm goes off at 3:45 and I managed everything at breakfast buffet bar fruit. Parents then gave me a lift and I was fully distracted by sourcing a pump and admiring the shiny chain after heavy rain overnight. Wales is unique for it’s long run to transition and consequently there are strict rules on the fourth pink bag for your runners. I had forgotten the sticker and spent my remaining pre race time finding a way to stick my number to my bag. The seeded swim queue threads its way through the streets of Tenby and I made my way through the crowds to the 1:10 marker, which it turns out didn’t exist. I was up near the front with a good few others starting to question our swim abilities. I enjoyed another rendition of the Welsh national anthem followed by ACDC’s Thunderstruck and we were soon in the water. Wales has to be my favourite triathlon swim; the sea is a warm 16.5 degrees, the salt water gives you some extra buoyancy and the hundreds of barrel jellyfish lay low so you’re blissfully unaware that they are even there. The Aussie exit is also brilliant as standing up effectively resets your body and you run back in the water having clocked your time eager to go a little faster. Final swim time 1:08, 3 min down on last year but small trade off given the extra focus on the bike this year. A quick game face pose for the camera and after what seems a lifetime I’m onto the bike.
        <br /><br />
        2017 was the first year cycling with a power meter and I consequently had an elaborate power plan tailored precisely to the terrain and forecasted micro climates…this left me watching half the field pass me. I did manage to pass a good few on the second lap but it was disappointing all the same so I had decided to be more aggressive on the bike this year. 250W average for first 20km was definitely a bit keen but I consequently was not penalised on the no overtaking sections near Angle and was able to benefit more from the tailwind heading back to Tenby. Nutrition was tried and tested in Austria, and involved taking Clif bar quarters every 15 minutes, and Enervit isotonic at most aid stations. This set me up for the two cheeky hills in Saundersfoot; the first of which saps your energy before you tackle the second with its incredible support. You feel you have to put on a show all the same and fortunately can recover on the fast downhill section into Tenby before heading out onto the second loop. It then gets very quiet for 10km before you beginning the second lap; it turned out all oil had been removed from the bike overnight and the squeaking was pretty annoying…for everyone as another cyclist kindly pointed out. I was definitely starting to feel it but managed to sustain 210W average, 10W more than last year on the TT. Having spent the first half the year getting comfortable on a TT bike I had no reservations taking it to Wales and if you have the option would recommend it. After 6:08, I was finally returning to Tenby, 42 minutes quicker than last year.
        <br /><br />
        For the first time I remembered to remove shoes before dismounting and was greeted with running barefoot on fairly rough tarmac. Possibly not the best start to a 42km run but I ended up 33rd fastest in T2, it does help! Spurred on by my coach in first 1km, I find my agreed pace much quicker this time round and start to prepare myself for the first of four descents up to New Hedges. The run course is cruel, the race director has agreed both times but the support is incredible…there isn’t a quiet moment and you feel everybody is vouching for you to keep moving and smiling. The hill is definitely taking more of toll compared to last year, and lap 3 is slower but again I found another gear on the final lap, safe in the knowledge that the hill will soon be behind you. 3:41, 11 minute more than last year but a decent bike performance. 11:05 overall; I would have been delighted to break 11 here but after placing 50th last year I hoped even more to place in top 40 this year, so 24th was a real bonus.
        <br /><br />
        I was kidding myself attending the Kona awards in the hope of a freak roll down the following day; it was brilliant seeing Gerard accept his slot but to also find myself on stage collecting the club prize on behalf of the four Pulsers racing this year, fantastic effort by all. I sheepishly walked around town with the trophy concealed…I was still a mad 50 min away from a Podium prize but it was added fuel on the fire and IM Cork 2019 can’t come sooner, 39 weeks and counting!`
    },
    {
        ID: 2,
        Show: true,
        Title: "IM Austria 2018",
        Date: new Date('2018-07-22'),
        Image: 'assets/austria2018.jpg',
        Swim: 4155000, Bike: 19175000, Run: 12883000, Overall: 36213000,
        Body: `Austria 2017 wasn’t meant to be after breaking my back snowboarding in January, so instead I spectated and having already decided against Austria 2018, the temptation of much of Pulse club registering the next day proved too much.
        <br /><br />
        Start of 2018, strictly no snow activities, and I decided after seeing decent improvement since moving to long distance triathlon I’d opt for a coach to help address weaknesses. I had a good swim and run at IM Wales the previous year but the bike was disappointing (6:40). I had a sub 10 in mind for Austria and picked up a second hand Cannondale Slice TT bike and some aero wheels. I was also registered for London marathon in April so focused on the bike in Jan and Feb and moved over to long hill runs ahead of London. Sub 3hr was on the cards but a combination of sickness leading up to the race and hot conditions on race day meant I seriously overheated 25km into the run after which point it was a case of just getting to the finish. I can’t remember crossing the finish line and was delirious as medics tried to cool me down. Not a good start and a serious question mark over whether I can handle heat, like Austria might experience. A few weeks later I managed to completely mess up my nutrition at the double Olympic in Athy; after a decent bike and start to the run I rapidly faded to a walk/run effort. So not the smoothest lead up but I wanted to make sure that i learnt from my mistakes namely factoring in race conditions for pace, and controlling nutrition and hydration. For the latter I bought all the Enervit nutrition that would be available on the bike course, increased my electrolyte intake in training, and figured out how to fit it all to the bike.
        <br /><br />
        I flew out to Munich Friday morning and was relieved to have my bike box rolled over to me at the other end. I then rented a car and after some confusion escaping Munich with its orbital motorway closed I made it to Klagenfurt 5 hours later and just in time for registration. Saturday revolved around trying out the canal part of the swim early with the sunrise, reconstructing the bike, doing a quick brick in what was now 30 degrees heat. Two quick takeaways: black aero helmet without visor is cool enough once you get moving, and saddle mounted bottle cages require some practice (half of the session was spent in a lay by doing circles until I had this figured out).
        <br /><br />
        Race day, 3:30AM alarm and hotel kindly put on breakfast. Two other couples were competing it was perfect distraction with both being seasoned IM participants reassuring you that this is completely normal. It was a 20 min drive out to the spot I’d found by chance the previous year and the scenic drive through mountains helped ease the nerves. On reflection it’s not the best place to park but it was one less variable to worry about and the walk over kept me occupied. Previous day transitions are easy to prepare for having done everything the day before, so you end up busying yourself with last minute changes. Definitely worth minimising last minute changes! I forgot my power meter battery but figured this was lower on the priorities and reverted to heart rate for the race.
        <br /><br />
        I joined the massive queue for restrooms, which ended up leaving a couple of minutes to get to the swim start. The gun for the pros went off while I was standing in line, and I started to worry but it proved a good distraction and I bumped into my old boss for quick chat. I finally ran over to the swim start and we started to enter the water. The first 500m of the swim always makes me question why i put myself through such stress and you just have to keep reminding yourself that this will pass after the first buoy. I started in the <1:10 group and emerged after 1:09, previous shorter distance races had me at slower paces so it’s so good knowing you can find some feet and stick with them for the whole distance. I hadn’t properly tested some new mirror goggles and one of my contacts got away 5 minutes into the swim.
        <br /><br />
        Bike leg
        <br /><br />
        No issues in transition: I had picked out some landmarks for the bike for a change and was soon out of T1. The course was already busy heading out and it was hard to hold back with HR hitting 150 for first 10min. This soon decreased to 135 and based on Wales the previous year I knew this was manageable and that I should be wary of this dropping on the in the second lap. The bike course in Austria is stunning and there is great support on the hills, although Wales still has the edge. Following on from Oliver’s nutrition video, I had 3 Cliff bars broken into pieces with a watch reminder every 15 min to fuel/hydrate. The on course isotonic is really dilute so I picked up 3 x 500ml bottles after each hill. I assumed any time gain would be due to my eager start but on reflection I was 12 minutes slower for the second lap over the course so pacing could have been better (most people experienced significant laps though as wind picked up). (5:19)
        <br /><br />
        <img src="assets/bikeLapComparison.png" width="80%"  />
        <br /><br />
        At the end of the bike leg while others were unclipping on the bike I didn’t twig but was otherwise quick enough out of T2 and legs felt decent for the run. Run course is a 5km out and back in either direction, with 3 opportunities to pass by the finish line, nice touch. Only thing worse than a morning hot marathon is one starting in the heat of the day however all fears were dispelled when I reached the first aid station and discovered cups of ice and sponges…this would have been amazing in London. Heart rate barely crept above 140 and I fell into a keen 4:45/km pace with the real chance of a sub 10.
        <br /><br />
        <img src="assets/bikeLapComparison.png" width="80%" />        
        <br /><br />
        I managed to maintain the pace without increasing HR for first 23km but the second half involved a lot more walking through aid stations and while the pace was still there, my average reduced from 4:50km/min to 5:21km/min ~11min. I also really appreciate all the Pulse support out on the run course; it makes all the difference particularly when you know when to expect it.
        <br /><br />
        My swim was also much slower relative to my age group so I feel I could have made up a few minutes there. I’m delighted with the time, it wasn’t a sub 10 but if I’d pushed it on the run like in London it may have been much worse and I was able to enjoy some sightseeing in Munich the following day.`
    },
    {
        ID: 3,
        Show: true,
        Title: "IM Wales 2017",
        Date: new Date('2017-09-10'),
        Image: 'assets/wales2017.jpg',
        Swim: 3952000, Bike: 24464000, Run: 12598000, Overall: 41014000,
        Body: `After a couple of surprise results at Challenge Galway and Dublin Marathon last year I was far too eager to do it all over again and promptly signed up for Austria and Wales. My somewhat ambitious goal was a sub 10 in Austria with it being one of the quicker courses and so I got to work on my bike with a new power meter and trainer road. It was going great, with my FTP increasing week on week.
        <br /><br />
        I managed to get a week snowboarding in the alps and was getting a kick out of being able to last all day benefiting from all the training. Unfortunately fitness is no substitute for skill and it wasn’t long before I found myself dealing with a broken back. My Doctor was keen for me to return to the pool as soon as I could and while making the difficult decision to unplug from Austria being able to swim meant the minor inconvenience served as fuel on the fire. Two months later I was back on the bike doing my favourite sportives, one more month had me back running so I ready for some national series action.
        <br /><br />
        The sprints and olympics were a perfect opportunity to experiment with the power meter, and by adhering to target power I had confidence that the run would be manageable. I also took part in a DCU study, which involved hooking myself up to breathing apparatus and doing 1min threshold efforts until fail week after week. If you can I’d really recommend doing something like this as it really helps explore ones limitations plus it helps provide a little context to the numbers.
        <br /><br />
        I peaked a little early on the bike having pushed myself at Gira (brilliant closed race in Belfast) and Wicklow 200, practically putting it rest while I spent the 2 months leading up to Wales working on the swim and run. Swimming involved 3 pulses sessions a week plus the Monday sea swim and I found the extra session really helped to maintain technique. The Howth aquathlon series is good for injecting some open water racing early in the season and the ocean breaker sessions at Killiney helped remove a tendency to hold back in fear of the worst.
        <br /><br />
        Wales is a convenient race, €120 return for the car ferry allowed me to accommodate every possible eventuality, which is a good thing given wales reputation for variable conditions. I had soaked up hours of video footage for the event and had overplayed thunderstruck and eye of the tiger in the lead up as I feared an inevitable adrenaline rush. The scale was also so different to Galway the previous year with 1800 vs 350 participants. The rolling start was a little more energetic than expected; having self-seeded on making the final turn onto the beach it was more of a mass charge into the 18 degrees water…so lucky. The buoys are a decent size, so no issues with sighting with one placed immediately below the red lifeguard house. The sea was actually pretty calm and made for a really enjoyable swim. There’s lots of talk about the 1 mile climb to transition but the five person deep crowds lining up all the way to T1 distract you from the discomfort. Stephen followed shortly after in T1 and it was great to see a familiar face as I put on an extra jersey and promptly emptied my pockets on the floor.
        <br /><br />
        I had previously been out on the bike course in rain a few weeks earlier so conditions were actually better now, a small boost as we were all made very aware that rain was on its way. Part of my experimenting with power involved splitting the bike up into 48 sections with varying target power based on forecasted wind and elevation data using Best Bike Split. I stuck to this with 70% FTP effort but it’s no fun being passed by bike after bike. Everybody seemed to be going for but perhaps it’s partly because I’m so used to being further back on the swim. 2hrs and I finally start to pass people, partly due to the rain. I’m relieved I have the jersey at this point; the rain is coming down and the course begins to get a little technical.
        <br /><br />
        Finally I turn right for the final drag into Tenby. When I had looked at this weeks earlier are decided I was done for the day and promptly hopped into the car. After all the previous climbs it was just another hill and the promise of stepping off the bike without event meant you barely noticed it. My lower back was pretty sore at this point and you begin wondering what those first few steps on the run will feel like. WC, into T2 and just being able to straighten out your back feels amazing. Also the sun was starting to break out and Tenby is ready to cheer you on for the run.
        <br /><br />
        My approach to running is a little less scientific; I pick a pace that I like, ideally rounded to the minute and stubbornly maintain an average pace. My quads are usually the first to complain where hills are involved both in running and biking, and so I was afraid what the downhills might do if I adopted a slow up-fast down approach. Ian suggested I keep it as steady as possible and I was surprised how well it worked. After each climb the prospect of one less sighting of the hill really drives you on along with the incredible experience of support on every street in Tenby as you zigzag your way through the town. I felt decent throughout the run with the exception of a quiver of the calf on the final hill. The fear of it suddenly cramping made me ease off slightly and go straight for the tortilla crisps. I’ve never eaten them on a run, which sounds alarm bells but they taste amazing and something to consider in training. These and cola comfortably got me through the run, neither a fancy form of race nutrition.
        <br /><br />
        The finish line seem to come soon enough and I believe the pacing on the bike played a massive part in this. I’m still scratching my head as to how the winner managed a time of 5:03, 30 seconds off the bike course PB in less than ideal conditions, and this will definitely be my focus over the winter months for Austria next year.`,
    },
    {
        ID: 4,
        Show: true,
        Title: "Challenge Galway",
        Date: new Date('2016-06-19'),
        Image: 'assets/cork2019.jpg',
        Swim: 0, Bike: 0, Run: 0, Overall: 0,
        Body: `
        Before 2013 I had only met one ‘Ironman’ and couldn’t get my head around the swim alone. I never seemed to be able to grasp it at school, spending lessons half blind and unable to hear anything going on. I’ve always been a bit hopeless at sport too but my competitive streak decided to finally make an appearance when my boss asked if any of the team would like to join in with the DCT sprint 2 months away. I swapped my MTB for a road bike, and joined Pulse having seen them fly past me a few weeks early in Blessington. A week later I was introduced to Wicklow and couldn’t believe what I had been missing. Next up Killarney and it’s not long before I’m needing to be escorted back to the coast at snail pace by Chris with no wetsuit, sorry Chris. Race day soon arrives and adrenaline outweighs competency as I find myself wondering what I’m doing in the freezing Liffey river chaos. I finally get out and get a boost on land. DCT is a fantastic first race as you’ll soon find yourself in good company on the 4/7 lap cycle course competing with all abilities. Dingle olympic a few months later was distinctly quieter with a good dose of jellyfish, sea mist and local roads thrown into the mix.
        <br /><br />
        2 years on and having built confidence more than anything else joined 70 odd other club members in registering for Dublin 70.3. Falling off the bike resulted in an overly generous 2 month taper but I managed to break 6 hours, which was all I needed to convince myself that Ironman was a ‘good’ idea. Chris had mentioned his 2 year plan towards an Ironman goal a year earlier and it was amazing seeing it come to fruition.
        <br /><br />
        September 2015 and I find myself registered for Challenge Galway, partly due to a pushy website that wouldn’t stop reminding me I hadn’t completed registration. I soon picked up a copy of Be Ironfit by Don Fink, discovered that the Pulse club sessions aligned perfectly, and started early December. Monday Joe’s S&C, Tuesday Kevin’s 90min spin, Wednesday Alison’s spin+treadmill, Thursday morning swim, Saturday club spin, Sunday Pheonix park running. The club offers so much with such supportive and knowledgeable members at its heart.
        <br /><br />
        Soon it was time to test the waters and having read somewhere that race experience was key I didn’t hold back on signing up for events. Quest Glendolough, Belfield duathlons, Howth and pulse aquathons, Lough Cutra half, Triathy double, Limerick half marathon, and the excellent club TTs. Additionally the thought of long bike rides in the early wetter months can be off-putting but they can still be enjoyable. Eager to keep up with Andrea we planned a few mad days of cycling; March-time Wicklow 200, Dublin to Limerick cycle (followed by limerick half), a ‘mock’ Ironman, Dublin to Newry, and mountain biking/trail runs at Ticknock. I was soon getting a feel for what a day’s exertion might entail.
        <br /><br />
        A week out from the big day and I opt for some ill-advised white water rafting, which ends with me limping for the preceding days. I seem to have a habit of doing something silly before marathons, having failed to make the start for the previous 2 Dublin marathons.
        <br /><br />
        Race day and I’m glad to have my family to distract me from the day ahead. I managed to find an Airbnb 10min down the beach from the start and it really must have helped with the nerves. I’m feeling ready and the not knowing if I’ll be able to run later removes some of the pressure. We enter the 15 degrees water and are soon on our way. I place myself right of the group and it ends up being very similar to Athy a few weeks earlier, touching plant life with every stroke, which helps keep me calm in the initial frenzy and I eventually find my pace. 1:07 later and I’m already being cheered by some of Pulse who had managed to make it down to Oranmore (really appreciated!).
        <br /><br />
        The wet conditions are perfect for someone living in Ireland, and I’m bracing myself for the post Gort track, which I soon discover has been been resurfaced and I find myself amongst a group of 2 or 3 cyclists who push each other through the remainder of the course. The fog starts to build up and I lose myself through the middle section when I get a welcome boost from Eithne in the rain. A few sketchy hairpins, a long drag up to Corkscrew hill and I’m finally on the coastal road back to Galway. I’m overwhelmed by the group of Pulsers as I enter T2 and more than ready to stretch out my back on the run. The weather has subsided and again like Athy I just have to complete 4 laps without the thought of a marathon entering my mind. The knee feels ok, can’t believe my luck and can only put it down to adrenaline, excited and relief in my back after 6:10 on the bike.
        <br /><br />
        There are already a good few out on the run course, and I feel like I’m making progress and looking forward to the next aid station and seeing Pulse and family after each loop. Finally 11 hours and 9 minutes later I have all 4 bands and make the final turn towards the red carpet.
        <br /><br />
        It meant so much to be able to share that experience with the people I had trained with week on week since December and I’m looking forward to being there in Frankfurt when many of them will be racing.
        <br /><br />
        A big thank you to everyone in the club. I’m not the most vocal of members but I really do enjoy all aspects of the club; club training weekends, club races, coached pool sessions, Sunday runs, club cycles, TTs, spin sessions, S&C, Killiney open water swims, Corkagh brick sessions, and the breadth of experience within the club. There really is so much being offered. Special mention to Joe (S&C sessions), the swim coaches (Dave, Colin and Alan), Kevin, Alison, Andrea, and Chris.
        `
    },
    {ID: 1, Date: new Date(2015,2,28), Image: "", Body: "", Show: false, Title: "SRAC", Swim: 0, Bike: 10787000, Run: 0, Overall: 10787000},
    {ID: 2, Date: new Date(2015,3,11), Image: "", Body: "", Show: false, Title: "SPAR 10km", Swim: 0, Bike: 2514000, Run: 0, Overall: 2514000},
    {ID: 3, Date: new Date(2015,4,24), Image: "", Body: "", Show: false, Title: "Lough Cutra Olympic", Swim: 0, Bike: 0, Run: 0, Overall: 0},
    {ID: 4, Date: new Date(2015,7,9), Image: "", Body: "", Show: false, Title: "IM 70.3 Dublin", Swim: 3085000, Bike: 10976000, Run: 6394000, Overall: 20455000},
    {ID: 5, Date: new Date(2015,7,23), Image: "", Body: "", Show: false, Title: "DCT Olympic", Swim: 1981000, Bike: 4842000, Run: 2776000, Overall: 9599000},
    {ID: 6, Date: new Date(2016,5,4), Image: "", Body: "", Show: false, Title: "Athy Double Olympic", Swim: 3632000, Bike: 8979000, Run: 5589000, Overall: 18200000},
    {ID: 7, Date: new Date(2016,5,26), Image: "", Body: "", Show: false, Title: "Challenge Galway", Swim: 4049000, Bike: 22221000, Run: 13157000, Overall: 39427000},
    {ID: 8, Date: new Date(2016,6,31), Image: "", Body: "", Show: false, Title: "Belfast Olympic", Swim: 1769000, Bike: 3887000, Run: 2481000, Overall: 8137000},
    {ID: 9, Date: new Date(2016,7,20), Image: "", Body: "", Show: false, Title: "Tri Hook", Swim: 888000, Bike: 2452000, Run: 1308000, Overall: 4648000},
    {ID: 10, Date: new Date(2016,7,21), Image: "", Body: "", Show: false, Title: "Sean Kelly Sportive", Swim: 0, Bike: 20648000, Run: 0, Overall: 20648000},
    {ID: 11, Date: new Date(2016,8,11), Image: "", Body: "", Show: false, Title: "Glendalough 3.9km", Swim: 4301000, Bike: 0, Run: 0, Overall: 4301000},
    {ID: 12, Date: new Date(2016,9,30), Image: "", Body: "", Show: false, Title: "Dublin Marathon", Swim: 0, Bike: 0, Run: 10796000, Overall: 10796000},
    {ID: 13, Date: new Date(2016,10,26), Image: "", Body: "", Show: false, Title: "Run the Line", Swim: 0, Bike: 0, Run: 9365000, Overall: 9365000},
    {ID: 14, Date: new Date(2017,2,12), Image: "", Body: "", Show: false, Title: "VO2 Cycle", Swim: 0, Bike: 17905000, Run: 0, Overall: 17905000},
    {ID: 15, Date: new Date(2017,4,22), Image: "", Body: "", Show: false, Title: "Howth Aquathlon", Swim: 1380000, Bike: 0, Run: 15720000, Overall: 17100000},
    {ID: 16, Date: new Date(2017,5,4), Image: "", Body: "", Show: false, Title: "Gran Fondo Gira Belfast", Swim: 0, Bike: 22231000, Run: 0, Overall: 22231000},
    {ID: 17, Date: new Date(2017,5,11), Image: "", Body: "", Show: false, Title: "Wicklow 200", Swim: 0, Bike: 27914000, Run: 0, Overall: 27914000},
    {ID: 18, Date: new Date(2017,5,17), Image: "", Body: "", Show: false, Title: "Westport Sprint", Swim: 714000, Bike: 2057000, Run: 1129000, Overall: 3900000},
    {ID: 19, Date: new Date(2017,6,15), Image: "", Body: "", Show: false, Title: "Two Province Sprint", Swim: 820000, Bike: 1824000, Run: 1232000, Overall: 3876000},
    {ID: 20, Date: new Date(2017,7,12), Image: "", Body: "", Show: false, Title: "Caroline Kearney", Swim: 1513000, Bike: 3855000, Run: 2305000, Overall: 7673000},
    {ID: 21, Date: new Date(2017,7,27), Image: "", Body: "", Show: false, Title: "DCT Olympic", Swim: 1605000, Bike: 3951000, Run: 2344000, Overall: 7900000},
    {ID: 22, Date: new Date(2017,8,10), Image: "", Body: "", Show: false, Title: "IM Wales", Swim: 3930000, Bike: 24409000, Run: 12539000, Overall: 40878000},
    {ID: 23, Date: new Date(2017,8,23), Image: "", Body: "", Show: false, Title: "DC Half Marathon", Swim: 0, Bike: 0, Run: 5134000, Overall: 5134000},
    {ID: 24, Date: new Date(2018,2,24), Image: "", Body: "", Show: false, Title: "SRAC", Swim: 0, Bike: 15043000, Run: 0, Overall: 15043000},
    {ID: 25, Date: new Date(2018,4,27), Image: "", Body: "", Show: false, Title: "Lough Cutra Olympic", Swim: 1881000, Bike: 4738000, Run: 2377000, Overall: 8996000},
    {ID: 26, Date: new Date(2018,5,2), Image: "", Body: "", Show: false, Title: "Athy Double", Swim: 3561000, Bike: 8274000, Run: 5654000, Overall: 17489000},
    {ID: 27, Date: new Date(2018,5,16), Image: "", Body: "", Show: false, Title: "Westport Sprint", Swim: 794000, Bike: 2216000, Run: 1135000, Overall: 4145000},
    {ID: 28, Date: new Date(2018,6,1), Image: "", Body: "", Show: false, Title: "IM Austria", Swim: 4196000, Bike: 19152000, Run: 12884000, Overall: 36232000},
    {ID: 29, Date: new Date(2018,6,28), Image: "", Body: "", Show: false, Title: "Tyrone Half", Swim: 2071000, Bike: 8931000, Run: 5579000, Overall: 16581000},
    {ID: 30, Date: new Date(2018,7,11), Image: "", Body: "", Show: false, Title: "CK Duathlon", Swim: 1186000, Bike: 3991000, Run: 2480000, Overall: 7657000},
    {ID: 31, Date: new Date(2018,8,9), Image: "", Body: "", Show: false, Title: "IM Wales", Swim: 4105000, Bike: 21700000, Run: 13275000, Overall: 39080000},
    {ID: 32, Date: new Date(2018,8,23), Image: "", Body: "", Show: false, Title: "Charleville HM", Swim: 0, Bike: 0, Run: 5122000, Overall: 5122000},
    {ID: 33, Date: new Date(2019,0,12), Image: "", Body: "", Show: false, Title: "Art O'Neill", Swim: 0, Bike: 0, Run: 35350000, Overall: 35350000},
    {ID: 34, Date: new Date(2019,4,26), Image: "", Body: "", Show: false, Title: "Lough Cutra Olympic", Swim: 2243000, Bike: 4289000, Run: 2610000, Overall: 9142000},
    {ID: 35, Date: new Date(2019,5,8), Image: "", Body: "", Show: false, Title: "Westport Olympic", Swim: 1604000, Bike: 3964000, Run: 2412000, Overall: 7980000},
    {ID: 36, Date: new Date(2019,5,23), Image: "", Body: "", Show: false, Title: "IM Cork", Swim: 0, Bike: 22166000, Run: 15243000, Overall: 37409000},
    {ID: 37, Date: new Date(2019,7,24), Image: "", Body: "", Show: false, Title: "Jailbreak Olympic", Swim: 1838000, Bike: 3524000, Run: 2228000, Overall: 7590000},
    {ID: 38, Date: new Date(2019,7,31), Image: "", Body: "", Show: false, Title: "Lost sheep", Swim: 2724000, Bike: 9438000, Run: 5783000, Overall: 17945000},
    {ID: 39, Date: new Date(2019,8,28), Image: "", Body: "", Show: false, Title: "Moby Dick", Swim: 1108000, Bike: 1811000, Run: 1436000, Overall: 4355000},
];